# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Sat Mar  4 19:41:42 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.ruleBookTreeWidget = QtGui.QTreeWidget(self.frame)
        self.ruleBookTreeWidget.setObjectName("ruleBookTreeWidget")
        self.ruleBookTreeWidget.headerItem().setText(0, "1")
        self.ruleBookTreeWidget.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.ruleBookTreeWidget)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.rightFrameLayout = QtGui.QVBoxLayout(self.frame_2)
        self.rightFrameLayout.setObjectName("rightFrameLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectedItemsTreeWidget = QtGui.QTreeWidget(self.frame_2)
        self.selectedItemsTreeWidget.setMaximumSize(QtCore.QSize(16777215, 225))
        self.selectedItemsTreeWidget.setObjectName("selectedItemsTreeWidget")
        self.selectedItemsTreeWidget.headerItem().setText(0, "1")
        self.selectedItemsTreeWidget.header().setVisible(False)
        self.horizontalLayout.addWidget(self.selectedItemsTreeWidget)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.moveUpInTreeButton = QtGui.QPushButton(self.frame_2)
        self.moveUpInTreeButton.setObjectName("moveUpInTreeButton")
        self.verticalLayout_3.addWidget(self.moveUpInTreeButton)
        self.moveDownInTreeButton = QtGui.QPushButton(self.frame_2)
        self.moveDownInTreeButton.setEnabled(True)
        self.moveDownInTreeButton.setObjectName("moveDownInTreeButton")
        self.verticalLayout_3.addWidget(self.moveDownInTreeButton)
        self.previewPushButton = QtGui.QPushButton(self.frame_2)
        self.previewPushButton.setObjectName("previewPushButton")
        self.verticalLayout_3.addWidget(self.previewPushButton)
        self.savePushButton = QtGui.QPushButton(self.frame_2)
        self.savePushButton.setObjectName("savePushButton")
        self.verticalLayout_3.addWidget(self.savePushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.rightFrameLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreate_Report = QtGui.QAction(MainWindow)
        self.actionCreate_Report.setObjectName("actionCreate_Report")
        self.menuFile.addAction(self.actionCreate_Report)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUpInTreeButton.setText(QtGui.QApplication.translate("MainWindow", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDownInTreeButton.setText(QtGui.QApplication.translate("MainWindow", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.previewPushButton.setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.savePushButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_Report.setText(QtGui.QApplication.translate("MainWindow", "Create Report", None, QtGui.QApplication.UnicodeUTF8))

